INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
('boosterbox', 'Boosterbox', 0,0,0),
('boosterpack', 'Boosterpack', 0,0,0),
('abra', 'Abra', 0,0,0),
('aerodactyl', 'Aerodactyl', 0,0,0),
('alakazam', 'Alakazam', 0,0,0),
('arbok', 'Arbok', 0,0,0),
('arcanine', 'Arcanine', 0,0,0),
('articuno', 'Articuno', 0,0,0),
('beedrill', 'Beedrill', 0,0,0),
('bellsprout', 'Bellsprout', 0,0,0),
('blastoise', 'Blastoise', 0,0,0),
('boulderbadge', 'Boulder Badge', 0,0,0),
('butterfree', 'Butterfree', 0,0,0),
('cascadebadge', 'Cascade Badge', 0,0,0),
('caterpie', 'Caterpie', 0,0,0),
('chansey', 'Chansey', 0,0,0),
('charizard', 'Charizard', 0,0,0),
('charmander', 'Charmander', 0,0,0),
('charmeleon', 'Charmeleon', 0,0,0),
('clefable', 'Clefable', 0,0,0),
('clefairy', 'Clefairy', 0,0,0),
('cloyster', 'Cloyster', 0,0,0),
('cubone', 'Cubone', 0,0,0),
('dewgong', 'Dewgong', 0,0,0),
('diglett', 'Diglett', 0,0,0),
('ditto', 'Ditto', 0,0,0),
('dodrio', 'Dodrio', 0,0,0),
('doduo', 'Doduo', 0,0,0),
('dragonair', 'Dragonair', 0,0,0),
('dragonite', 'Dragonite', 0,0,0),
('dratini', 'Dratini', 0,0,0),
('drowzee', 'Drowzee', 0,0,0),
('dugtrio', 'Dugtrio', 0,0,0),
('earthbadge', 'Earth Badge', 0,0,0),
('eevee', 'Eevee', 0,0,0),
('ekans', 'Ekans', 0,0,0),
('electabuzz', 'Electabuzz', 0,0,0),
('electrode', 'Electrode', 0,0,0),
('exeggcute', 'Exeggcute', 0,0,0),
('exeggutor', 'Exeggutor', 0,0,0),
('farfetchd', 'Farfetchd', 0,0,0),
('fearow', 'Fearow', 0,0,0),
('flareon', 'Flareon', 0,0,0),
('gastly', 'Gastly', 0,0,0),
('gengar', 'Gengar', 0,0,0),
('geodude', 'Geodude', 0,0,0),
('gloom', 'Gloom', 0,0,0),
('graveler', 'Graveler', 0,0,0),
('grimer', 'Grimer', 0,0,0),
('growlithe', 'Growlithe', 0,0,0),
('gyarados', 'Gyarados', 0,0,0),
('haunter', 'Haunter', 0,0,0),
('hitmonchan', 'Hitmonchan', 0,0,0),
('hitmonlee', 'Hitmonlee', 0,0,0),
('horsea', 'Horsea', 0,0,0),
('hypno', 'Hypno', 0,0,0),
('ivysaur', 'Ivysaur', 0,0,0),
('jigglypuff', 'Jigglypuff', 0,0,0),
('jolteon', 'Jolteon', 0,0,0),
('jynx', 'Jynx', 0,0,0),
('kabuto', 'Kabuto', 0,0,0),
('kabutops', 'Kabutops', 0,0,0),
('kadabra', 'Kadabra', 0,0,0),
('kakuna', 'Kakuna', 0,0,0),
('kangaskhan', 'Kangaskhan', 0,0,0),
('kingler', 'Kingler', 0,0,0),
('koffing', 'Koffing', 0,0,0),
('krabby', 'Krabby', 0,0,0),
('lapras', 'Lapras', 0,0,0),
('lickitung', 'Lickitung', 0,0,0),
('machamp', 'Machamp', 0,0,0),
('machoke', 'Machoke', 0,0,0),
('machop', 'Machop', 0,0,0),
('magikarp', 'Magikarp', 0,0,0),
('magmar', 'Magmar', 0,0,0),
('magnemite', 'Magnemite', 0,0,0),
('magneton', 'Magneton', 0,0,0),
('mankey', 'Mankey', 0,0,0),
('marowak', 'Marowak', 0,0,0),
('marshbadge', 'Marsh Badge', 0,0,0),
('meowth', 'Meowth', 0,0,0),
('metapod', 'Metapod', 0,0,0),
('mew', 'Mew', 0,0,0),
('mewtwo', 'Mewtwo', 0,0,0),
('moltres', 'Moltres', 0,0,0),
('mrmime', 'Mr Mime', 0,0,0),
('muk', 'Muk', 0,0,0),
('nidoking', 'Nidoking', 0,0,0),
('nidoqueen', 'Nidoqueen', 0,0,0),
('nidoran', 'Nidoran', 0,0,0),
('nidorina', 'Nidorina', 0,0,0),
('nidorino', 'Nidorino', 0,0,0),
('ninetales', 'Ninetales', 0,0,0),
('oddish', 'Oddish', 0,0,0),
('omanyte', 'Omanyte', 0,0,0),
('omastar', 'Omastar', 0,0,0),
('onix', 'Onix', 0,0,0),
('paras', 'Paras', 0,0,0),
('parasect', 'Parasect', 0,0,0),
('persian', 'Persian', 0,0,0),
('pidgeotto', 'Pidgeotto', 0,0,0),
('pidgey', 'Pidgey', 0,0,0),
('pikachu', 'Pikachu', 0,0,0),
('pinsir', 'Pinsir', 0,0,0),
('poliwag', 'Poliwag', 0,0,0),
('polywhirl', 'Polywhirl', 0,0,0),
('poliwrath', 'Poliwrath', 0,0,0),
('ponyta', 'Ponyta', 0,0,0),
('porygon', 'Porygon', 0,0,0),
('primeape', 'Primeape', 0,0,0),
('psyduck', 'Psyduck', 0,0,0),
('raichu', 'Raichu', 0,0,0),
('rainbowbadge', 'Rainbow Badge', 0,0,0),
('rapidash', 'Rapidash', 0,0,0),
('raticate', 'Raticate', 0,0,0),
('rattata', 'Rattata', 0,0,0),
('rhydon', 'Rhydon', 0,0,0),
('rhyhorn', 'Rhyhorn', 0,0,0),
('sandshrew', 'Sandshrew', 0,0,0),
('sandslash', 'Sandslash', 0,0,0),
('scyther', 'Scyther', 0,0,0),
('seadra', 'Seadra', 0,0,0),
('seaking', 'Seaking', 0,0,0),
('seel', 'Seel', 0,0,0),
('shellder', 'Shellder', 0,0,0),
('slowbro', 'Slowbro', 0,0,0),
('slowpoke', 'Slowpoke', 0,0,0),
('snorlax', 'Snorlax', 0,0,0),
('soulbadge', 'Soul Badge', 0,0,0),
('spearow', 'Spearow', 0,0,0),
('squirtle', 'Squirtle', 0,0,0),
('starmie', 'Starmie', 0,0,0),
('staryu', 'Staryu', 0,0,0),
('tangela', 'Tangela', 0,0,0),
('tauros', 'Tauros', 0,0,0),
('tentacool', 'Tentacool', 0,0,0),
('tentacruel', 'Tentacruel', 0,0,0),
('thunderbadge', 'Thunder Badge', 0,0,0),
('togepi', 'Togepi', 0,0,0),
('trophybadge', 'Trophy Badge', 0,0,0),
('vaporeon', 'Vaporeon', 0,0,0),
('venomoth', 'Venomoth', 0,0,0),
('venonat', 'Venonat', 0,0,0),
('venusaur', 'Venusaur', 0,0,0),
('victreebel', 'Victreebel', 0,0,0),
('vileplume', 'Vileplume', 0,0,0),
('volcanobadge', 'Volcano Badge', 0,0,0),
('voltorb', 'Voltorb', 0,0,0),
('vulpix', 'Vulpix', 0,0,0),
('wartortle', 'Wartortle', 0,0,0),
('weedle', 'Weedle', 0,0,0),
('weepinbell', 'Weepinbell', 0,0,0),
('weezing', 'Weezing', 0,0,0),
('wigglytuff', 'Wigglytuff', 0,0,0),
('zapdos', 'Zapdos', 0,0,0),
('zubat', 'Zubat', 0,0,0),
('bulbasaur', 'Bulbasaur', 0,0,0),
('pidgeot', 'Pidgeot', 0,0,0),
('blastoisev', 'Blastoise V', 0,0,0),
('charizardv', 'Charizard V', 0,0,0),
('mewv', 'Mew V', 0,0,0),
('pikachuv', 'Pikachu V', 0,0,0),
('snorlaxv', 'Snorlax V', 0,0,0),
('venusaurv', 'Venusaur V', 0,0,0),
('blastoisevmax', 'Blastoise V MAX', 0,0,0),
('mewtwogx', 'Mewtwo GX', 0,0,0),
('snorlaxvmax', 'Snorlax V MAX', 0,0,0),
('venusaurvmax', 'Venusaur V MAX', 0,0,0),
('charizardvmax', 'Charizard V MAX', 0,0,0),
('pikachuvmax', 'Pikachu V MAX', 0,0,0),
('rainbowmewtwogx', 'Rainbow Mewtwo', 0,0,0),
('rainbowvmaxcharizard', 'Rainbow Charizard', 0,0,0),
('rainbowvmaxpikachu', 'Rainbow Pikachu', 0,0,0),
('rainbowvmaxsnorlax', 'Rainbow Snorlax', 0,0,0),
('pokebox', 'Pokebox', 0,0,0),;
